# Données des loyers

In [1]:
import pandas as pd

# Import des datasets depuis data gouv pour les appartements 1 et 2 pièces
loyers_2024 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/89956da9-5b9b-41d7-8703-18dbec4d54a2', encoding='latin-1', sep=';')
loyers_2023 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/edadefbc-9707-45ef-a841-283608709e58', encoding='latin-1', sep=';')
loyers_2022 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/7141612b-8029-44a4-a048-921a85a47b1f', encoding='latin-1', sep=';')

# Ajout d'une colonne pour l'année du fichier
loyers_2024['annee'] = 2024
loyers_2023['annee'] = 2023
loyers_2022['annee'] = 2022

# Concaténer les données des loyers
loyers_full = pd.concat([loyers_2024, loyers_2023, loyers_2022], ignore_index=True)

## Exploration des loyers

In [20]:
display(loyers_full, loyers_full.dtypes)

,id_zone,INSEE_C,LIBGEO,EPCI,DEP,REG,loypredm2,lwr.IPm2,upr.IPm2,TYPPRED,nbobs_com,nbobs_mail,R2_adj,annee
0,1,31529,Samouillan,200072643,31,76,"10,8814528339144","8,68960978837338","13,6261602834145",maille,2,505,"0,68491517971051",2024
1,1,31343,Mirambeau,200072643,31,76,"10,8814528339144","8,68960978837338","13,6261602834145",maille,0,505,"0,68491517971051",2024
2,1,32185,Lalanne-Arqué,200072320,32,76,"10,8814528339144","8,68960978837338","13,6261602834145",maille,0,505,"0,68491517971051",2024
3,1,31008,Anan,200072643,31,76,"10,8814528339144","8,68960978837338","13,6261602834145",maille,0,505,"0,68491517971051",2024
4,1,32410,Samatan,243200599,32,76,"12,2633693497271","9,70583304077554","15,4948294676011",commune,142,505,"0,68491517971051",2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104905,DOM_7,97308,Saint-Georges,249730052,973,3,"15,0575936963594","12,0749243849611","18,7770225879865",maille,2,2662,"0,551070876764774",2022
104906,DOM_7,97310,Roura,249730045,973,3,"15,0575936963594","12,0749243849611","18,7770225879865",maille,8,2662,"0,551070876764774",2022
104907,DOM_7,97352,Saül,249730037,973,3,"15,0575936963594","12,0749243849611","18,7770225879865",maille,0,2662,"0,551070876764774",2022
104908,DOM_7,97314,Ouanary,249730052,973,3,"15,0575936963594","12,0749243849611","18,7770225879865",maille,0,2662,"0,551070876764774",2022
104909,DOM_8,97309,Remire-Montjoly,249730045,973,3,"19,297791906581","15,7109858930642","23,703462978355",commune,725,725,"0,548309150554959",2022

id_zone       object
INSEE_C       object
LIBGEO        object
EPCI          object
DEP           object
REG            int64
loypredm2     object
lwr.IPm2      object
upr.IPm2      object
TYPPRED       object
nbobs_com      int64
nbobs_mail     int64
R2_adj        object
annee          int64
dtype: object

In [5]:
loyers_full.loc[loyers_full['LIBGEO'].str.contains('Mérignac') & loyers_full['INSEE_C'].str.contains('33281')]

,id_zone,INSEE_C,LIBGEO,EPCI,DEP,REG,loypredm2,lwr.IPm2,upr.IPm2,TYPPRED,nbobs_com,nbobs_mail,R2_adj,annee
7463,1473,33281,Mérignac,243300316,33,75,"17,3211307731372","14,5231792360587","20,6581194367701",commune,6853,7051,"0,628501351976129",2024
45043,1859,33281,Mérignac,243300316,33,75,"16,8353834324416","14,0099460091962","20,2306372295286",commune,4021,4021,"0,614830898027762",2023
76332,1451,33281,Mérignac,243300316,33,75,"16,6314695477889","12,982729355201","21,3056724631034",commune,3656,35464,"0,609933135175862",2022

# Données des valeurs foncières

In [24]:
# Import des données depuis data gouv
dvf_2024 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/5ffa8553-0e8f-4622-add9-5c0b593ca1f8', compression='zip', encoding='latin-1', sep='|')
dvf_2023 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/bc213c7c-c4d4-4385-bf1f-719573d39e90', compression='zip', encoding='latin-1', sep='|')
dvf_2022 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/b4f43708-c5a8-4f30-80dc-7adfa1265d74', compression='zip', encoding='latin-1', sep='|')

# Ajout d'une colonne pour l'année du fichier
dvf_2024['annee'] = 2024
dvf_2023['annee'] = 2023
dvf_2022['annee'] = 2022

C:\Users\Thibaut\AppData\Local\Temp\ipykernel_23448\3539765361.py:2: DtypeWarning: Columns (14,18,23,24,26,28,29,30,31,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  dvf_2024 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/5ffa8553-0e8f-4622-add9-5c0b593ca1f8', compression='zip', encoding='latin-1', sep='|')
C:\Users\Thibaut\AppData\Local\Temp\ipykernel_23448\3539765361.py:3: DtypeWarning: Columns (14,18,23,24,26,28,31,32,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  dvf_2023 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/bc213c7c-c4d4-4385-bf1f-719573d39e90', compression='zip', encoding='latin-1', sep='|')
C:\Users\Thibaut\AppData\Local\Temp\ipykernel_23448\3539765361.py:4: DtypeWarning: Columns (18,23,24,26,28,29,31,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  dvf_2022 = pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/b4f43708-c5a8-4f30-80dc-7adfa1265d74', compression='zip', encoding='latin-1', sep='|')

In [25]:
# Concaténer les données des loyers
dvf_full = pd.concat([dvf_2024, dvf_2023, dvf_2022], ignore_index=True)

# Nettoyage des données
cols_to_keep = ['Date mutation', 'Nature mutation', 'Type local', 'Nombre pieces principales', 'Valeur fonciere', 'Code postal','Commune', 'Code departement', 'Code commune', '1er lot', 'Surface Carrez du 1er lot', 'annee']

dvf_filtered = dvf_full[(dvf_full['Nature mutation'].str.contains('vente', case=False)) &
                        (dvf_full['Type local'].str.contains('appartement', case=False)) &
                        (dvf_full['Nombre de lots'] == 1) &
                        (dvf_full['Nombre pieces principales'] <= 2.0)
                ]

dvf_filtered = dvf_filtered[cols_to_keep].dropna()

## Exploration des DVF

In [26]:
display(dvf_filtered, dvf_filtered.dtypes)

,Date mutation,Nature mutation,Type local,Nombre pieces principales,Valeur fonciere,Code postal,Commune,Code departement,Code commune,1er lot,Surface Carrez du 1er lot,annee
131,10/01/2024,Vente,Appartement,2.0,"110000,00",1200.0,VALSERHONE,1,33,102.0,"45,67",2024
138,04/01/2024,Vente,Appartement,1.0,"148000,00",1120.0,DAGNEUX,1,142,3.0,"39,11",2024
259,03/01/2024,Vente,Appartement,1.0,"147000,00",1210.0,FERNEY-VOLTAIRE,1,160,104.0,"30,00",2024
269,12/01/2024,Vente,Appartement,2.0,"205000,00",1170.0,GEX,1,173,112.0,"54,09",2024
425,03/01/2024,Vente,Appartement,2.0,"152000,00",1960.0,PERONNAS,1,289,3.0,"57,60",2024
...,...,...,...,...,...,...,...,...,...,...,...,...
11937501,22/03/2022,Vente,Appartement,1.0,"232650,00",75013.0,PARIS 13,75,113,7,"28,25",2022
11937515,05/05/2022,Vente,Appartement,2.0,"400000,00",75015.0,PARIS 15,75,115,13,"35,03",2022
11937522,12/07/2022,Vente,Appartement,1.0,"110000,00",75012.0,PARIS 12,75,112,69,"15,39",2022
11937523,02/11/2022,Vente,Appartement,1.0,"220000,00",75011.0,PARIS 11,75,111,116,"19,01",2022
11937526,17/05/2022,Vente,Appartement,2.0,"2100000,00",75016.0,PARIS 16,75,116,5,"194,28",2022

Date mutation                 object
Nature mutation               object
Type local                    object
Nombre pieces principales    float64
Valeur fonciere               object
Code postal                  float64
Commune                       object
Code departement              object
Code commune                   int64
1er lot                       object
Surface Carrez du 1er lot     object
annee                          int64
dtype: object